/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2016-02-09 19:20:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/resources/include/include.jsp", Long.valueOf(1439292837107L));
    _jspx_dependants.put("/WEB-INF/tags/nav-bar.tag", Long.valueOf(1454741671149L));
    _jspx_dependants.put("/WEB-INF/tags/community-nav.tag", Long.valueOf(1454767875308L));
    _jspx_dependants.put("/WEB-INF/tld/GachonLineTag.tld", Long.valueOf(1440491493441L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgachonTag_005fhtml;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgachonTag_005fhtml = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fgachonTag_005fhtml.release();
    _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /resources/include/include.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("CONTEXT_PATH");
      // /resources/include/include.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(request.getContextPath() );
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f5(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_gachonTag_005fhtml_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /resources/include/include.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("PATH_JS");
    // /resources/include/include.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/resources/include/include.jsp(11,0) '${CONTEXT_PATH }/resources/js'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${CONTEXT_PATH }/resources/js",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /resources/include/include.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("PATH_IMAGES");
    // /resources/include/include.jsp(12,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/resources/include/include.jsp(12,0) '${CONTEXT_PATH }/resources/image'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${CONTEXT_PATH }/resources/image",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /resources/include/include.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("PATH_JQUERY");
    // /resources/include/include.jsp(13,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/resources/include/include.jsp(13,0) '${CONTEXT_PATH }/resources/plugin/jquery'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${CONTEXT_PATH }/resources/plugin/jquery",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f4.setParent(null);
    // /resources/include/include.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setVar("PATH_CSS");
    // /resources/include/include.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/resources/include/include.jsp(14,0) '${CONTEXT_PATH }/resources/css'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${CONTEXT_PATH }/resources/css",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
    if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f5.setParent(null);
    // /resources/include/include.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f5.setVar("PATH_PLUGIN");
    // /resources/include/include.jsp(15,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/resources/include/include.jsp(15,0) '${CONTEXT_PATH }/resources/plugin'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${CONTEXT_PATH }/resources/plugin",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
    if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
    return false;
  }

  private boolean _jspx_meth_gachonTag_005fhtml_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gachonTag:html
    com.myspring.gachon.tags.HtmlTag _jspx_th_gachonTag_005fhtml_005f0 = (com.myspring.gachon.tags.HtmlTag) _005fjspx_005ftagPool_005fgachonTag_005fhtml.get(com.myspring.gachon.tags.HtmlTag.class);
    _jspx_th_gachonTag_005fhtml_005f0.setPageContext(_jspx_page_context);
    _jspx_th_gachonTag_005fhtml_005f0.setParent(null);
    int _jspx_eval_gachonTag_005fhtml_005f0 = _jspx_th_gachonTag_005fhtml_005f0.doStartTag();
    if (_jspx_eval_gachonTag_005fhtml_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        if (_jspx_meth_gachonTag_005fscript_005f0(_jspx_th_gachonTag_005fhtml_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("<body>\r\n");
        out.write("\r\n");
        out.write("\t<!-- 구분은 하나의 변수로하고 변수는 두개로 즉 구분자와 그룹자 두개를 넘겨준다. -->\r\n");
        out.write("\t<!-- 속성 아직 안만들어 놨어요 이거는 임시방편으로 만든 태그라이브러리이고  /WEB-INF/tags/nav-bar.tag \r\n");
        out.write("에다가 링크를 수정해주세양! 나중에 tag class 만들때 참고할게양 ! -->\r\n");
        out.write("\r\n");
        out.write("\t\r\n");
        out.write("\r\n");
        out.write("\t");
        if (_jspx_meth_GachonTag_005fnav_002dbar_005f0(_jspx_th_gachonTag_005fhtml_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t<div class=\"container\">\r\n");
        out.write("\r\n");
        out.write("\t\t<!-- 커뮤니케이션 게시판에 사용할 nav-Bar 필요한 데이터는 divs만 받으면 된다.\r\n");
        out.write("\t하나의 컨트롤러 그리고 단 하나의 메서드 로 페이지를 구분한다.\r\n");
        out.write("\t -->\r\n");
        out.write("\t\t");
        if (_jspx_meth_GachonTag_005fcommunity_002dnav_005f0(_jspx_th_gachonTag_005fhtml_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_gachonTag_005fhtml_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t<div>\r\n");
        out.write("\t\t\t<div class=\"table-responsive\">\r\n");
        out.write("\t\t\t\t<table id=\"boardList\" data-toggle=\"table\" data-show-columns=\"true\"\r\n");
        out.write("\t\t\t\t\tdata-search=\"true\" data-show-refresh=\"true\"\r\n");
        out.write("\t\t\t\t\tdata-show-toggle=\"false\" data-show-export=\"true\"\r\n");
        out.write("\t\t\t\t\tdata-pagination=\"true\">\r\n");
        out.write("\t\t\t\t\t<thead>\r\n");
        out.write("\t\t\t\t\t\t<tr>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-field=\"boardNo\" class=\"col-sm-1 text_center\">글 번호</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-field=\"title\" class=\"col-sm-5 text_center\">제 목</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-field=\"createUser\" class=\"col-sm-2 text_center\">작성자</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-field=\"createDate\" class=\"col-sm-2 text_center\">작성일</th>\r\n");
        out.write("\t\t\t\t\t\t\t<th data-field=\"viewCount\" class=\"col-sm-1 text_center\">조회</th>\r\n");
        out.write("\t\t\t\t\t\t</tr>\r\n");
        out.write("\t\t\t\t\t</thead>\r\n");
        out.write("\t\t\t\t</table>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\r\n");
        out.write("\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t<div class=\"col-sm-4\">&nbsp;</div>\r\n");
        out.write("\t\t\t\t<div class=\"col-sm-4\">&nbsp;</div>\r\n");
        out.write("\t\t\t\t<div class=\"col-sm-4\">\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fchoose_005f0(_jspx_th_gachonTag_005fhtml_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t</div>\r\n");
        out.write("\t</div>\t\r\n");
        out.write("</body>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("//덧글 불러오기\r\n");
        out.write("function commentList(boardNo){\r\n");
        out.write("\tvar dataForm = {\r\n");
        out.write("\t\tboardNo : boardNo\t\r\n");
        out.write("\t};\r\n");
        out.write("\t$.post(\"/community/reply\",{boardNo:boardNo},function(data){\r\n");
        out.write("\t\tvar replies = document.getElementById('replies');\r\n");
        out.write("\t\twhile (replies.firstChild) {\r\n");
        out.write("\t\t    replies.removeChild(replies.firstChild);\r\n");
        out.write("\t\t}\r\n");
        out.write("\t\treplies.className = \"well\";\r\n");
        out.write("\t\tfor(var reply in data){\r\n");
        out.write("\r\n");
        out.write("\t\t\tvar div1 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div2 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div3 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div4 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div5 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div6 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div7 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div8 = document.createElement('div');\r\n");
        out.write("\t\t\tvar div9 = document.createElement('div');\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tvar input1 = document.createElement('input');\r\n");
        out.write("\t\t\tvar input2 = document.createElement('input');\r\n");
        out.write("\t\t\tvar input3 = document.createElement('input');\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tvar textarea1 = document.createElement('textarea');\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tdiv1.className = \"row\";\r\n");
        out.write("\t\t\tdiv1.style=\"background-color:#fff;margin-bottom:1em;padding-top:0.7em;\";\r\n");
        out.write("\t\t\r\n");
        out.write("\t\t\tdiv2.className = \"col-sm-2\";\r\n");
        out.write("\t\t\tdiv3.className = \"col-sm-7\";\r\n");
        out.write("\t\t\tdiv4.className = \"col-sm-3\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tdiv5.className = \"form-group\";\r\n");
        out.write("\t\t\tdiv6.className = \"form-group\";\r\n");
        out.write("\t\t\tdiv7.className = \"form-group\";\r\n");
        out.write("\t\t\tdiv8.className = \"form-group\";\r\n");
        out.write("\t\t\tdiv9.className = \"form-group\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\ttextarea1.className = \"form-control\";\r\n");
        out.write("\t\t\ttextarea1.rows = \"4\";\r\n");
        out.write("\t\t\ttextarea1.readOnly = true;\r\n");
        out.write("\t\t\ttextarea1.value = data[reply].comment1;\r\n");
        out.write("\t\t\ttextarea1.id = data[reply].commentNo+\"_comment1\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tinput1.type = \"text\";\r\n");
        out.write("\t\t\tinput1.className = \"form-control\";\r\n");
        out.write("\t\t\tinput1.readOnly=true;\r\n");
        out.write("\t\t\tinput1.value = data[reply].createUser;\r\n");
        out.write("\t\t\tinput1.id = data[reply].commentNo+\"_name\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tinput2.type = \"text\";\r\n");
        out.write("\t\t\tinput2.className = \"form-control\";\r\n");
        out.write("\t\t\tinput2.readOnly=true;\r\n");
        out.write("\t\t\tinput2.value = data[reply].createId;\r\n");
        out.write("\t\t\tinput2.id = data[reply].commentNo+\"_id\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tinput3.type = \"text\";\r\n");
        out.write("\t\t\tinput3.className = \"form-control\";\r\n");
        out.write("\t\t\tinput3.readOnly=true;\r\n");
        out.write("\t\t\tinput3.value = data[reply].createDate;\r\n");
        out.write("\t\t\tinput3.id = data[reply].commentNo+\"_date\";\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tif('");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("' == data[reply].createId){\r\n");
        out.write("\t\t\t\tvar input4 = document.createElement('input');\r\n");
        out.write("\t\t\t\tvar input5 = document.createElement('input');\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\tinput4.type = \"button\";\r\n");
        out.write("\t\t\t\tinput4.className = \"col-sm-6 btn btn-warning\";\r\n");
        out.write("\t\t\t\tinput4.value = \"삭제\";\r\n");
        out.write("\t\t\t\tinput4.id = data[reply].commentNo+\"_delete\";\r\n");
        out.write("\t\t\t\tinput4.onclick = replyDelete;\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\tinput5.type = \"button\";\r\n");
        out.write("\t\t\t\tinput5.className = \"col-sm-6 btn btn-success\";\r\n");
        out.write("\t\t\t\tinput5.value = \"수정\";\r\n");
        out.write("\t\t\t\tinput5.id = data[reply].commentNo+\"_update\";\r\n");
        out.write("\t\t\t\tinput5.onclick = replyUpdate;\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t\tdiv9.appendChild(input4);\r\n");
        out.write("\t\t\t\tdiv9.appendChild(input5);\r\n");
        out.write("\t\t\t}else{\r\n");
        out.write("\t\t\t\tdiv9.innerHTML = \"&nbsp;\";\r\n");
        out.write("\t\t\t}\r\n");
        out.write("\t\t\tdiv5.appendChild(input1);\r\n");
        out.write("\t\t\tdiv6.appendChild(input2);\r\n");
        out.write("\t\t\tdiv7.appendChild(textarea1);\r\n");
        out.write("\t\t\tdiv8.appendChild(input3);\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tdiv2.appendChild(div5);\r\n");
        out.write("\t\t\tdiv2.appendChild(div6);\r\n");
        out.write("\t\t\tdiv3.appendChild(div7);\r\n");
        out.write("\t\t\tdiv4.appendChild(div8);\r\n");
        out.write("\t\t\tdiv4.appendChild(div9);\r\n");
        out.write("\t\t\t\r\n");
        out.write("\t\t\tdiv1.appendChild(div2);\r\n");
        out.write("\t\t\tdiv1.appendChild(div3);\r\n");
        out.write("\t\t\tdiv1.appendChild(div4);\r\n");
        out.write("\t\t\treplies.appendChild(div1);\r\n");
        out.write("\t\t}\r\n");
        out.write("\t\t\r\n");
        out.write("\t});\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("//댓글 작성\r\n");
        out.write("function replySubmit(){\r\n");
        out.write("\tvar replyComment1 =document.getElementById('replyComment1');\r\n");
        out.write("\tvar dataForm ={\r\n");
        out.write("\t\tboardNo : '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("',\r\n");
        out.write("\t\tcomment1 : replyComment1.value,\r\n");
        out.write("\t\tcreateUser : document.getElementById('replyCreateUser').value,\r\n");
        out.write("\t\tcreateId : document.getElementById('replyCreateId').value\r\n");
        out.write("\t};\r\n");
        out.write("\t$.post(\"/community/reply/write\",dataForm,function(data){\r\n");
        out.write("\t\tGachonNoty.showCustomNoty(dataForm.createUser+'님의 \\n [덧글]이 [등록]되었습니다.');\r\n");
        out.write("\t\treplyComment1.value=\"\";\r\n");
        out.write("\t\tcommentList(dataForm.boardNo);\r\n");
        out.write("\t});\r\n");
        out.write("}\r\n");
        out.write("//댓글 삭제\r\n");
        out.write("function replyDelete(event){\r\n");
        out.write("\tif(confirm(\"해당 댓글을 정말 삭제 하시겠습니까?\")){\r\n");
        out.write("\r\n");
        out.write("\t\tvar commentNo = event.toElement.id.split('_')[0];\r\n");
        out.write("\t\tvar comment1 = document.getElementById(commentNo+'_comment1').value;\r\n");
        out.write("\t\tvar dataForm ={\r\n");
        out.write("\t\t\tboardNo : '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("',\r\n");
        out.write("\t\t\tcommentNo : commentNo\r\n");
        out.write("\t\t};\r\n");
        out.write("\t\t$.post(\"/community/reply/delete\",dataForm,function(data){\r\n");
        out.write("\t\t\tGachonNoty.showCustomNoty(dataForm.createUser+'님의 \\n [덧글]이 [수정]되었습니다.');\r\n");
        out.write("\t\t\tcommentList(dataForm.boardNo);\r\n");
        out.write("\t\t});\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("//댓글 수정\r\n");
        out.write("function replyUpdate(event){\r\n");
        out.write("\tvar commentNo = event.toElement.id.split('_')[0];\r\n");
        out.write("\tvar comment1 = document.getElementById(commentNo+'_comment1').value;\r\n");
        out.write("\tvar dataForm ={\r\n");
        out.write("\t\tboardNo : '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("',\r\n");
        out.write("\t\tcommentNo : commentNo,\r\n");
        out.write("\t\tcomment1 : comment1\r\n");
        out.write("\t};\r\n");
        out.write("\tvar textarea1 = document.getElementById(commentNo+'_comment1');\r\n");
        out.write("\tvar updateBtn = document.getElementById(commentNo+'_update');\r\n");
        out.write("\tvar deleteBtn = document.getElementById(commentNo+'_delete');\r\n");
        out.write("\r\n");
        out.write("\tif(!(textarea1.readOnly)){\r\n");
        out.write("\t\tif(confirm(\"해당 댓글을 수정하시겠습니까?\")){\r\n");
        out.write("\t\t\t$.post(\"/community/reply/update\",dataForm,function(data){\r\n");
        out.write("\t\t\t\tGachonNoty.showCustomNoty(dataForm.createUser+'님의 \\n [덧글]이 [수정]되었습니다.');\r\n");
        out.write("\t\t\t\tcommentList(dataForm.boardNo);\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("\t\t\t});\r\n");
        out.write("\t\t}\r\n");
        out.write("\t}else{\r\n");
        out.write("\t\tdeleteBtn.value=\"취소\"\r\n");
        out.write("\t\tdeleteBtn.onclick=replyUpdateCancle;\r\n");
        out.write("\t\tupdateBtn.value=\"!제출!\";\r\n");
        out.write("\t\t\r\n");
        out.write("\t\ttextarea1.onkeydown=repliesInput;\r\n");
        out.write("\t\ttextarea1.readOnly=false;\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("//댓글 수정버튼을 누르고 나면 나타나는 삭제버튼에 대한 이벤트\r\n");
        out.write("function replyUpdateCancle(){\r\n");
        out.write("\tcommentList('");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("');\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("function boardDelete(){\r\n");
        out.write("\tif(confirm(\"해당 게시글을 삭제하시겠습니까?\")){\r\n");
        out.write("\t\t$( \"boardDelete\" ).submit(function( event ) {\r\n");
        out.write("\t\t\tGachonNoty.showCustomNoty('덧글 삭제가 완료되었습니다.');\r\n");
        out.write("\t\t});\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("function boardDelete(){\r\n");
        out.write("\tif(confirm(\"해당 게시글을 수정하시겠습니까?\")){\r\n");
        out.write("\t\t$( \"boardDelete\" ).submit(function( event ) {\r\n");
        out.write("\t\t\tGachonNoty.showCustomNoty('덧글 삭제가 완료되었습니다.');\r\n");
        out.write("\t\t});\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("</script>\r\n");
        out.write("\r\n");
        int evalDoAfterBody = _jspx_th_gachonTag_005fhtml_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_gachonTag_005fhtml_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fgachonTag_005fhtml.reuse(_jspx_th_gachonTag_005fhtml_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fgachonTag_005fhtml.reuse(_jspx_th_gachonTag_005fhtml_005f0);
    return false;
  }

  private boolean _jspx_meth_gachonTag_005fscript_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_gachonTag_005fhtml_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gachonTag:script
    com.myspring.gachon.tags.ScriptTag _jspx_th_gachonTag_005fscript_005f0 = (com.myspring.gachon.tags.ScriptTag) _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable.get(com.myspring.gachon.tags.ScriptTag.class);
    _jspx_th_gachonTag_005fscript_005f0.setPageContext(_jspx_page_context);
    _jspx_th_gachonTag_005fscript_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_gachonTag_005fhtml_005f0);
    // /WEB-INF/views/community/Community.jsp(5,0) name = bootstrapTable type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_gachonTag_005fscript_005f0.setBootstrapTable("YES");
    int _jspx_eval_gachonTag_005fscript_005f0 = _jspx_th_gachonTag_005fscript_005f0.doStartTag();
    if (_jspx_eval_gachonTag_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("<!-- 게시글 리스트들을 역할을 합니다. -->\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("\r\n");
        out.write("$(document).ready(function() {\r\n");
        out.write("\tlist();\r\n");
        out.write("\t$(function() {\r\n");
        out.write("\t\t$('#boardList').bootstrapTable().on('click-row.bs.table',function(e, row, $element) {\r\n");
        out.write("\t\t\tlocation.href=\"/community?divs=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("&boardNo=\"+row.boardNo;\r\n");
        out.write("\t\t});\r\n");
        out.write("\t});\r\n");
        out.write("});\r\n");
        out.write("\r\n");
        out.write("//댓글에 들어가는 인풋박스 검증하기\r\n");
        out.write("function replyInput(value) {\r\n");
        out.write("\tif (value.length > 2 && value.length < 1000) {\r\n");
        out.write("\t\tdocument.getElementById(\"replyNotice\").innerHTML = \"&nbsp;\";\r\n");
        out.write("\t\tdocument.getElementById(\"replySubmit\").disabled = false;\r\n");
        out.write("\t} else {\r\n");
        out.write("\t\tdocument.getElementById(\"replyNotice\").innerHTML = \"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;덧글이 너무 짧거나 너무 깁니다.1000글자 제한입니다.\";\r\n");
        out.write("\t\tdocument.getElementById(\"replySubmit\").disabled = true;\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("//댓글에 들어가는 인풋박스 검증하기\r\n");
        out.write("function repliesInput(event) {\r\n");
        out.write("\tvar commentNo = event.srcElement.id.split('_')[0];\r\n");
        out.write("\tvar value = event.srcElement.value;\r\n");
        out.write("\t\r\n");
        out.write("\tif (value.length > 2 && value.length < 1000) {\r\n");
        out.write("\t\tdocument.getElementById(commentNo+\"_update\").disabled = false;\r\n");
        out.write("\t} else {\r\n");
        out.write("\t\tdocument.getElementById(commentNo+\"_update\").disabled = true;\r\n");
        out.write("\t}\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("//리스트를 불러옵니다.\r\n");
        out.write("function list() {\r\n");
        out.write("\tvar dataForm = {\r\n");
        out.write("\t\ttype : '");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("'\r\n");
        out.write("\t};\r\n");
        out.write("\t$.ajax({\r\n");
        out.write("\t\ttype : \"POST\",\r\n");
        out.write("\t\turl : \"/community.select\",\r\n");
        out.write("\t\tcache : false,\r\n");
        out.write("\t\tasync : true,\r\n");
        out.write("\t\tdata : dataForm,\r\n");
        out.write("\t\tdataType : \"json\",\r\n");
        out.write("\t\tsuccess : function(response) {\r\n");
        out.write("\t\t\t$('#boardList').bootstrapTable('load', response);\r\n");
        out.write("\t\t},\r\n");
        out.write("\t\terror : function(request, status, errorThrown) {\r\n");
        out.write("\t\t\tGachonNoty.showAjaxErrorNoty(request, status, errorThrown);\r\n");
        out.write("\t\t}\r\n");
        out.write("\t});\r\n");
        out.write("}\r\n");
        out.write("\r\n");
        out.write("</script>\r\n");
        int evalDoAfterBody = _jspx_th_gachonTag_005fscript_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_gachonTag_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable.reuse(_jspx_th_gachonTag_005fscript_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fgachonTag_005fscript_0026_005fbootstrapTable.reuse(_jspx_th_gachonTag_005fscript_005f0);
    return false;
  }

  private boolean _jspx_meth_GachonTag_005fnav_002dbar_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_gachonTag_005fhtml_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  GachonTag:nav-bar
    org.apache.jsp.tag.webnav_002dbar_tag _jspx_th_GachonTag_005fnav_002dbar_005f0 = (new org.apache.jsp.tag.webnav_002dbar_tag());
    _jsp_instancemanager.newInstance(_jspx_th_GachonTag_005fnav_002dbar_005f0);
    _jspx_th_GachonTag_005fnav_002dbar_005f0.setJspContext(_jspx_page_context);
    _jspx_th_GachonTag_005fnav_002dbar_005f0.setParent(_jspx_th_gachonTag_005fhtml_005f0);
    // /WEB-INF/views/community/Community.jsp(72,1) name = name type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_GachonTag_005fnav_002dbar_005f0.setName((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    // /WEB-INF/views/community/Community.jsp(72,1) name = type type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_GachonTag_005fnav_002dbar_005f0.setType((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_GachonTag_005fnav_002dbar_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_GachonTag_005fnav_002dbar_005f0);
    return false;
  }

  private boolean _jspx_meth_GachonTag_005fcommunity_002dnav_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_gachonTag_005fhtml_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  GachonTag:community-nav
    org.apache.jsp.tag.webcommunity_002dnav_tag _jspx_th_GachonTag_005fcommunity_002dnav_005f0 = (new org.apache.jsp.tag.webcommunity_002dnav_tag());
    _jsp_instancemanager.newInstance(_jspx_th_GachonTag_005fcommunity_002dnav_005f0);
    _jspx_th_GachonTag_005fcommunity_002dnav_005f0.setJspContext(_jspx_page_context);
    _jspx_th_GachonTag_005fcommunity_002dnav_005f0.setParent(_jspx_th_gachonTag_005fhtml_005f0);
    // /WEB-INF/views/community/Community.jsp(79,2) name = divs type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_GachonTag_005fcommunity_002dnav_005f0.setDivs((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    _jspx_th_GachonTag_005fcommunity_002dnav_005f0.doTag();
    _jsp_instancemanager.destroyInstance(_jspx_th_GachonTag_005fcommunity_002dnav_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_gachonTag_005fhtml_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_gachonTag_005fhtml_005f0);
    // /WEB-INF/views/community/Community.jsp(81,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!(board eq null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t<script type=\"text/javascript\">\r\n");
        out.write("\t\t\t$(document).ready(function() {\r\n");
        out.write("\t\t\t\t$('html, body').animate({\r\n");
        out.write("\t\t\t\t\tscrollTop : $(\"#board\").offset().top - 30\r\n");
        out.write("\t\t\t\t}, 300);\r\n");
        out.write("\t\t\t});\r\n");
        out.write("\t\t\t</script>\r\n");
        out.write("\t\t\t<div id=\"board\">\r\n");
        out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 3em;\">\r\n");
        out.write("\t\t\t\t\t<div class=\"row form-row\">\r\n");
        out.write("\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2 attr_name \">제목</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<input id=\"title\" type=\"text\" class=\"form-control\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.LIST.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" readonly />\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\r\n");
        out.write("\t\t\t\t\t<div class=\"row form-row\">\r\n");
        out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4 attr_name \">이름</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<input id=\"createUser\" type=\"text\" class=\"form-control\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.LIST.createUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" readonly />\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4 attr_name \">학번</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-8\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<input id=\"createId\" type=\"text\" class=\"form-control\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.LIST.createId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" readonly />\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t<div class=\"well\">\r\n");
        out.write("\t\t\t\t\t<div class=\"row form-group\">\r\n");
        out.write("\t\t\t\t\t\t<label for=\"comment\">내용</label>\r\n");
        out.write("\t\t\t\t\t\t<div class=\"card-content card\"\r\n");
        out.write("\t\t\t\t\t\t\tstyle=\"height: 440px; overflow-y: scroll;\">\r\n");
        out.write("\t\t\t\t\t\t\t<div id=\"content\" style=\"border: none; background-color: #ffffff\">\r\n");
        out.write("\t\t\t\t\t\t\t\t");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.CONTENT.content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t<div id=\"replies\">\r\n");
        out.write("\r\n");
        out.write("\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("$(document).ready(function(){\r\n");
        out.write("\tcommentList('");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("');\r\n");
        out.write("});\r\n");
        out.write("</script>\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t</div>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/community/Community.jsp(128,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberId eq board.LIST.createId}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">&nbsp;</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\">&nbsp;</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-4\" style=\"padding-top: 1em;\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<form method=\"post\" id=\"boardDelete\" action=\"/community/delete\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"divs\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"boardNo\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" onclick=\"boardDelete()\" value=\"삭제하기\" class=\"col-sm-12 btn btn-warning\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<form method=\"post\" id=\"boardUpdate\" action=\"/community/update\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"divs\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" /> \r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"boardNo\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" value=\"수정하기\" class=\"col-sm-12 btn btn-success\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/community/Community.jsp(160,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!(LOGIN_MEMBER eq null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<div id=\"replyNotice\" class=\"row\">&nbsp;</div>\r\n");
        out.write("\t\t\t\t\t<div class=\"well\">\r\n");
        out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" id=\"replyCreateUser\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" readonly />\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input class=\"form-control\" type=\"text\" name=\"createId\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_MEMBER.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" id=\"replyCreateId\" readonly />\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-7\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<textarea onkeydown=\"replyInput(this.value)\" rows=\"4\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control\" type=\"text\" id=\"replyComment1\"></textarea>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"reset\" class=\"form-control btn btn-warning\" value=\"다시 작성\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
        out.write("\t\t\t\t\t\t\t\t\t<input type=\"submit\" onClick=\"replySubmit();\" id=\"replySubmit\" class=\"form-control btn btn-success\" value=\"덧글 달기\" />\r\n");
        out.write("\t\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_gachonTag_005fhtml_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_gachonTag_005fhtml_005f0);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/community/Community.jsp(214,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!(LOGIN_MEMBER eq null)}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t<form method=\"POST\" action=\"/community/write\">\r\n");
        out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"divs\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divs}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
        out.write("\" /> <input\r\n");
        out.write("\t\t\t\t\t\t\t\t\ttype=\"submit\" class=\"col-sm-11 btn btn-success\" style=\"margin-top: 1em; margin-left: 1em; margin-right: 1em;\"\r\n");
        out.write("\t\t\t\t\t\t\t\t\tvalue=\"글 쓰기\" />\r\n");
        out.write("\t\t\t\t\t\t\t</form>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t&nbsp;\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
